// Each project is told as a short story: a handful of chapters, each anchored to a real
// screenshot of the live site (public/projects/<id>/). `mobile` screenshots feed the
// "every screen" chapter. Theme colours re-skin the whole site while a project is open.
//
// fluidColor is picked so that, through the fluid layer's `difference` blend, the cursor
// trail paints roughly the brand accent on the light page background.

const img = (id, name) => `/projects/${id}/${name}.webp`;

const projects = [
  {
    id: 'allied-dc',
    title: 'Allied Data Center',
    shortTitle: 'Allied DC',
    link: '/projects/allied-dc',
    liveLink: 'https://www.allieddc.de/',
    domain: 'allieddc.de',
    img: img('allied-dc', 'cover'),
    date: '2026',
    company: 'Allied Data Center',
    sector: 'Critical Infrastructure',
    location: 'Frankfurt · Dubai',
    country: 'Germany',
    role: 'Design & Development',
    stack: ['Next.js', 'Tailwind CSS', 'German / English', 'SEO'],
    tagline: 'The infrastructure digital worlds run on, told as one clear engineering story.',
    featured: true,
    primary: '#0F172A',
    secondary: '#F1F5F9',
    accentColor: '#FFFFFF',
    fillColor: '#DBE7FB',
    menuColor: '#0A4FCB',
    menuFontColor: '#F1F5F9',
    fluidColor: '#E7A62E',
    facts: [
      { value: '200MW+', label: 'AI / data-centre capacity delivered' },
      { value: '99.98%', label: 'Tier III design uptime' },
      { value: '350+', label: 'In-house engineers' },
    ],
    story: [
      {
        label: 'The Brief',
        title: 'Make critical infrastructure feel calm.',
        text: 'Allied Data Center is the engineering and turnkey delivery partner behind data centres for hyperscalers, banks, telecoms and governments, from the first feasibility study to certified handover. Their promise is "one contract, one team, one result". The site had to carry that certainty to engineers, CFOs and investors in two languages, before anyone reads a spec sheet.',
        image: img('allied-dc', 's0'),
      },
      {
        label: 'The Structure',
        title: 'A homepage that reads like a programme plan.',
        text: 'I laid the page out the way ADC actually works: site selection and feasibility, ESG and energy, design and engineering management, then execution. Each phase is a card with a real photograph and one plain sentence, so the full development lifecycle reads top to bottom in a single scroll.',
        image: img('allied-dc', 's1'),
      },
      {
        label: 'The System',
        title: 'Everything critical, engineered together.',
        text: 'Eight capabilities, from AI factories to critical power, cooling and commissioning, sit in a numbered grid. A restrained palette of navy, slate and one signal blue, with generous white space, lets a very technical offer breathe instead of shout.',
        image: img('allied-dc', 's2'),
      },
      {
        label: 'The Spotlight',
        title: 'A stage for the AI factory.',
        text: 'GPU buyers get their own chapter: a full-bleed render and four numbered pillars covering high-density power, advanced cooling, high-speed connectivity and phased compute rollout. It turns "we can build AI infrastructure" into something you can picture.',
        image: img('allied-dc', 's3'),
      },
      {
        label: 'The Proof',
        title: 'Delivered work closes the argument.',
        text: 'Case studies such as the AI Cloud Prefab Data Center and the Mohammed Bin Zayed Data Center appear with client, scope and location. A De / En switch keeps both audiences one tap away.',
        image: img('allied-dc', 's4'),
      },
    ],
    mobile: [img('allied-dc', 'm0'), img('allied-dc', 'm1'), img('allied-dc', 'm2')],
    mobileText: 'Every grid folds into a single thumb-friendly column, and the language switch stays pinned in the header, so a site engineer on a phone gets the same story as an investor at a desk.',
  },
  {
    id: 'nyxt',
    title: 'Nyxt',
    shortTitle: 'Nyxt',
    link: '/projects/nyxt',
    liveLink: 'https://nyxt.in/',
    domain: 'nyxt.in',
    img: img('nyxt', 'cover'),
    date: '2026',
    company: 'Nyxt',
    sector: 'Content & Growth Agency',
    location: 'India',
    country: 'India',
    role: 'Design & Development',
    stack: ['Next.js', 'Tailwind CSS', 'Lenis', 'Video reels'],
    tagline: 'A content engineering agency that needed a site as sharp as its reels.',
    featured: true,
    primary: '#281E3C',
    secondary: '#FFF7FA',
    accentColor: '#FFFFFF',
    fillColor: '#FFE1EC',
    menuColor: '#E8286F',
    menuFontColor: '#FFFFFF',
    fluidColor: '#17CF8B',
    facts: [
      { value: '24M+', label: 'Views across clients' },
      { value: '440k+', label: 'Followers across clients' },
      { value: '32%', label: 'Increase in brand visibility' },
    ],
    story: [
      {
        label: 'The Brief',
        title: 'Not another social media agency.',
        text: 'Nyxt builds organic brand growth through content strategy, short-form video and personal branding. Their pitch is that content should be engineered, not posted and hoped for. The website had to feel as loud as a viral reel and as deliberate as a strategy deck.',
        image: img('nyxt', 's0'),
      },
      {
        label: 'The Argument',
        title: 'Most brands create content. Few engineer it.',
        text: 'Instead of a wall of services, the first thing you meet is a comparison. "The usual" on one side, "The Nyxt Way" on the other, four lines each. It is the whole sales conversation compressed into two cards.',
        image: img('nyxt', 's1'),
      },
      {
        label: 'The Method',
        title: 'Discover, engineer, grow.',
        text: 'The process runs in three numbered steps, followed by the results that matter to founders: views, followers and brand visibility, rendered as bold glossy stats in the brand gradient.',
        image: img('nyxt', 's2'),
      },
      {
        label: 'The Work',
        title: 'Built to be seen, designed to convert.',
        text: 'The portfolio is a swipeable wall of vertical video, the format Nyxt actually ships, with smooth scrolling so the page itself moves like a feed.',
        image: img('nyxt', 's3'),
      },
      {
        label: 'The Proof',
        title: 'Clients say it in their own words.',
        text: 'Testimonials from managing directors close the page, including Prime Vessels, whose showroom site is also in this portfolio. Then there is one form and one call to action: book a free strategy call.',
        image: img('nyxt', 's4'),
      },
    ],
    mobile: [img('nyxt', 'm0'), img('nyxt', 'm1'), img('nyxt', 'm2')],
    mobileText: 'Nyxt lives on Instagram, so the site is at home on a phone. The gradient hero, the comparison cards and the team grid all reflow portrait-first.',
  },
  {
    id: 'hexogt',
    title: 'HexoGT',
    shortTitle: 'HexoGT',
    link: '/projects/hexogt',
    liveLink: 'https://www.hexogt.com/',
    domain: 'hexogt.com',
    img: img('hexogt', 'cover'),
    date: '2026',
    company: 'Hexo Global Technologies',
    sector: 'Enterprise Technology',
    location: 'Bengaluru, India',
    country: 'India',
    role: 'Design & Development',
    stack: ['Next.js', 'Tailwind CSS', 'Lenis'],
    tagline: 'Cloud, cybersecurity and AI for enterprises that measure risk before reward.',
    featured: false,
    primary: '#1F2430',
    secondary: '#EEF4FF',
    accentColor: '#FFFFFF',
    fillColor: '#FFE7C7',
    menuColor: '#FF9408',
    menuFontColor: '#1F2430',
    fluidColor: '#1160F7',
    facts: [
      { value: '99.995%', label: 'System availability uptime' },
      { value: '42%', label: 'Infrastructure cost reduction' },
      { value: '75%', label: 'Security risk reduction' },
    ],
    story: [
      {
        label: 'The Brief',
        title: 'Enterprise buyers look for risk first.',
        text: 'Hexo Global Technologies designs, builds and secures systems across cloud, cybersecurity, data and AI, and digital engineering for banks, aerospace, semiconductor and mobility companies. Those buyers are sceptical by default, so the site leads with calm confidence rather than buzzwords.',
        image: img('hexogt', 's0'),
      },
      {
        label: 'The Capabilities',
        title: 'Eight services, one clear shelf.',
        text: 'Talent consulting, cloud, cybersecurity, data, AI and quantum, digital engineering, finance and risk, infrastructure and managed services each get a panel with one line of value and a direct "talk to us". Soft gradient tiles in the brand’s orange and indigo give a serious offer some warmth.',
        image: img('hexogt', 's1'),
      },
      {
        label: 'The Industries',
        title: 'Six industries in one screen.',
        text: 'Choose Banking, Aerospace and Defence, Semiconductor, Embedded Systems, Software and Platforms or Mobility, and the photograph and copy swap in place. Visitors find their own sector in one click without leaving the page.',
        image: img('hexogt', 's2'),
      },
      {
        label: 'The Numbers',
        title: 'Impact, stated plainly.',
        text: 'Availability, cost reduction, deployment speed and security results sit in a clean band of figures. Enterprise buyers want to see numbers, and here they get them.',
        image: img('hexogt', 's3'),
      },
      {
        label: 'The Case Studies',
        title: 'Stories from real engagements.',
        text: 'Case studies such as talent consulting for NBFC giant Manappuram Finance and a re-architected data platform lead into a consultation form, so moving from reading to talking takes one scroll.',
        image: img('hexogt', 's4'),
      },
    ],
    mobile: [img('hexogt', 'm0'), img('hexogt', 'm1'), img('hexogt', 'm2')],
    mobileText: 'On mobile the industry switcher becomes a row of swipeable chips, and the capability panels stack into cards that still show the orange call to action above the fold.',
  },
  {
    id: 'vectorton',
    title: 'Vectorton',
    shortTitle: 'Vectorton',
    link: '/projects/vectorton',
    liveLink: 'https://vectorton.com/',
    domain: 'vectorton.com',
    img: img('vectorton', 'cover'),
    date: '2026',
    company: 'Vectorton',
    sector: 'Data, AI & Quantum',
    location: 'Texas, USA',
    country: 'USA',
    role: 'Design & Development',
    stack: ['Next.js', 'Tailwind CSS', 'Dark design system'],
    tagline: 'Deep-tech engineering made intuitive, in the dark with one violet light.',
    featured: true,
    primary: '#F3EEFF',
    secondary: '#0B0716',
    accentColor: '#141118',
    fillColor: '#2A1F45',
    menuColor: '#BD92FE',
    menuFontColor: '#0B0716',
    fluidColor: '#B28BE8',
    facts: [
      { value: '3', label: 'Pillars: data, AI and quantum' },
      { value: '4', label: 'Service lines' },
      { value: 'Texas', label: 'Global HQ' },
    ],
    story: [
      {
        label: 'The Brief',
        title: 'Make the invisible feel precise.',
        text: 'Vectorton builds petabyte-scale data pipelines, enterprise AI and quantum research. It is powerful work that is hard to picture. The site had to feel premium and exact without burying visitors in jargon.',
        image: img('vectorton', 's0'),
      },
      {
        label: 'The Mood',
        title: 'Architecting the invisible.',
        text: 'I went dark: a near-black canvas, a single violet accent and a glowing gradient hero card. A bento grid pairs a holographic brain visual with Vision, Mission, Innovation and Integrity, the values behind the machines.',
        image: img('vectorton', 's1'),
      },
      {
        label: 'The Pillars',
        title: 'Data. Intelligence. Compute.',
        text: 'Three pillar cards explain the offer. The middle one, Artificial Intelligence, is lit in violet to lead the eye. Each card ends with its own call to action: talk to a data engineer, an AI engineer or the research team.',
        image: img('vectorton', 's2'),
      },
      {
        label: 'The Services',
        title: 'High-fidelity services.',
        text: 'AI solutions, consulting, data platforms and research are laid out as a quiet list, framed as long-term partnership rather than one-off projects.',
        image: img('vectorton', 's3'),
      },
      {
        label: 'The Close',
        title: 'Answers, then a conversation.',
        text: 'An FAQ handles the obvious questions, and a gradient contact panel asks the only one that matters: ready to re-engineer your infrastructure?',
        image: img('vectorton', 's4'),
      },
    ],
    mobile: [img('vectorton', 'm0'), img('vectorton', 'm1'), img('vectorton', 'm2')],
    mobileText: 'The dark system holds up on small screens: the hero card becomes full-bleed and the pillars stack with their violet highlight intact.',
  },
  {
    id: 'frames-by-monish',
    title: 'Frames by Monish',
    shortTitle: 'Frames by Monish',
    link: '/projects/frames-by-monish',
    liveLink: 'https://www.framesbymonish.in/',
    domain: 'framesbymonish.in',
    img: img('frames-by-monish', 'cover'),
    date: '2026',
    company: 'Monish Kumar Photography',
    sector: 'Wedding Photography',
    location: 'Kanyakumari, India',
    country: 'India',
    role: 'Design & Development',
    stack: ['HTML, CSS & JS', 'Bootstrap 5', 'Custom lightbox', 'WhatsApp inquiries'],
    tagline: 'A quiet cream frame around the moments that happen between the moments.',
    featured: true,
    primary: '#301E0E',
    secondary: '#FFFCF4',
    accentColor: '#FFFFFF',
    fillColor: '#F3E6CF',
    menuColor: '#301E0E',
    menuFontColor: '#FFFCF4',
    fluidColor: '#376AB8',
    facts: [
      { value: '5', label: 'Wedding stories told start to finish' },
      { value: '3', label: 'Cities: Chennai, Coimbatore, Bangalore' },
      { value: '1', label: 'Tap to a pre-filled WhatsApp inquiry' },
    ],
    story: [
      {
        label: 'The Brief',
        title: 'Get out of the way of the photographs.',
        text: 'Monish photographs weddings the way they feel: small, real moments in natural light. He is based in Kanyakumari and works across Chennai, Coimbatore and Bangalore. A photographer’s site should step back, so the design is a warm frame around his pictures.',
        image: img('frames-by-monish', 's0'),
      },
      {
        label: 'The Voice',
        title: '"Hello, I’m Monish."',
        text: 'The first section speaks in his voice, over a loose collage of black-and-white and colour frames. A Didone serif for headlines, a clean sans for body text, and a cream and espresso palette taken straight from the photographs.',
        image: img('frames-by-monish', 's1'),
      },
      {
        label: 'The Offer',
        title: 'Weddings, portraits, celebrations.',
        text: 'Three services sit on a deep brown band, each introduced by a photograph rather than an icon, with a link to a real story instead of a price list.',
        image: img('frames-by-monish', 's2'),
      },
      {
        label: 'The Stories',
        title: 'Every wedding told as a story.',
        text: 'Rohan and Kavya, "All the way to goodbye". Karthik and Divya, "Red earth, white walls". Each wedding runs from the first ritual to the last goodbye, in the order it happened. The same idea shapes this portfolio.',
        image: img('frames-by-monish', 's3'),
      },
      {
        label: 'The Inquiry',
        title: 'From a quote to a conversation.',
        text: '"The moments that happen between the moments" leads into a short inquiry form. On submit it opens WhatsApp with the couple’s details already filled in, so the first message is already half-written.',
        image: img('frames-by-monish', 's4'),
      },
    ],
    mobile: [img('frames-by-monish', 'm0'), img('frames-by-monish', 'm1'), img('frames-by-monish', 'm2')],
    mobileText: 'Portrait crops, generous type and big tap targets let the stories read like a photo album on a phone, with the inquiry one tap away.',
  },
  {
    id: 'prime-vessels',
    title: 'Prime Vessels',
    shortTitle: 'Prime Vessels',
    link: '/projects/prime-vessels',
    liveLink: 'https://primevessel.vercel.app/',
    domain: 'primevessel.vercel.app',
    img: img('prime-vessels', 'cover'),
    date: '2026',
    company: 'Prime Vessels',
    sector: 'Kitchenware Retail',
    location: 'Ettumanoor, Kerala',
    country: 'India',
    role: 'Design & Development',
    stack: ['Next.js', 'Tailwind CSS', 'Product catalogue', 'WhatsApp commerce'],
    tagline: 'A Kerala showroom of crockery, cutlery and cookware, open online.',
    featured: false,
    primary: '#172A3A',
    secondary: '#F7FAFC',
    accentColor: '#FFFFFF',
    fillColor: '#EAF3FA',
    menuColor: '#172A3A',
    menuFontColor: '#F7FAFC',
    fluidColor: '#3F87C9',
    facts: [
      { value: '4.7★', label: 'From 100+ customer reviews' },
      { value: '10', label: 'Curated categories' },
      { value: '1', label: 'Showroom in Ettumanoor' },
    ],
    story: [
      {
        label: 'The Brief',
        title: 'Bring the showroom online.',
        text: 'Prime Vessels is a showroom in Ettumanoor, Kerala, stocking everything from cast iron and brass to crockery, cutlery and kitchen appliances for homes, hotels and restaurants. People want to browse before they visit, or order with a WhatsApp message.',
        image: img('prime-vessels', 's0'),
      },
      {
        label: 'The Aisles',
        title: 'Ten categories, one glance.',
        text: 'Cast iron, brass, steel, crockery, cutlery, aluminium, appliances, décor and gifts are laid out like showroom aisles, with clean product cut-outs and an offer tile that breaks the grid.',
        image: img('prime-vessels', 's1'),
      },
      {
        label: 'The Shelf',
        title: 'Worth discovering.',
        text: 'Featured products show the discount, the price in rupees and the original MRP struck through, which is exactly the information a price-conscious buyer is looking for.',
        image: img('prime-vessels', 's2'),
      },
      {
        label: 'The Trust',
        title: 'Word of mouth, made visible.',
        text: 'A 4.7-star rating from more than 100 reviews anchors a carousel of real customer quotes, the kind of word-of-mouth a local business can’t buy.',
        image: img('prime-vessels', 's3'),
      },
      {
        label: 'The Brands',
        title: 'Names people already trust.',
        text: 'A scrolling strip of familiar kitchen brands leads into the footer’s showroom address and a floating WhatsApp button that follows you around the store.',
        image: img('prime-vessels', 's4'),
      },
    ],
    mobile: [img('prime-vessels', 'm0'), img('prime-vessels', 'm1'), img('prime-vessels', 'm2')],
    mobileText: 'The catalogue becomes a two-column grid sized for a thumb, and the WhatsApp button sits where the thumb already rests.',
  },
  {
    id: 'newmax-aqua',
    title: 'Newmax Aqua',
    shortTitle: 'Newmax Aqua',
    link: '/projects/newmax-aqua',
    liveLink: 'https://newmaxaqua.in/',
    domain: 'newmaxaqua.in',
    img: img('newmax-aqua', 'cover'),
    date: '2026',
    company: 'New Max Aqua',
    sector: 'Water & Solar Solutions',
    location: 'Kottayam · Ernakulam',
    country: 'India',
    role: 'Design & Development',
    stack: ['HTML5', 'Bootstrap', 'GSAP', 'Swiper', 'Before / after slider'],
    tagline: 'Pure water and clean energy, explained the way a technician would.',
    featured: false,
    primary: '#0E2350',
    secondary: '#F2F6FF',
    accentColor: '#FFFFFF',
    fillColor: '#DCEBFF',
    menuColor: '#007CFB',
    menuFontColor: '#FFFFFF',
    fluidColor: '#702AF6',
    facts: [
      { value: '17+', label: 'Purifier models' },
      { value: '9', label: 'Services, from RO to solar' },
      { value: '2', label: 'Branches across Kerala' },
    ],
    story: [
      {
        label: 'The Brief',
        title: 'Start with the question: is my water safe?',
        text: 'New Max Aqua sells, installs and services water purifiers, filtration vessels and solar systems across Kerala from Kottayam and Ernakulam. Customers usually arrive with one worry, so the site answers the way a technician would, starting with a water test.',
        image: img('newmax-aqua', 's0'),
      },
      {
        label: 'The Range',
        title: 'Complete care for water, solar and hygiene.',
        text: 'Nine services, from RO and UV purifiers to tank deep-cleaning, drip irrigation and home automation, each with an icon and one line. It is a one-stop shop that still scans in seconds.',
        image: img('newmax-aqua', 's1'),
      },
      {
        label: 'The Moment',
        title: 'See the difference pure water makes.',
        text: 'The most persuasive element on the page is a before-and-after slider. Drag it, and cloudy tap water becomes a clear glass. It does more than any paragraph about filtration could.',
        image: img('newmax-aqua', 's2'),
      },
      {
        label: 'The Catalogue',
        title: 'Pure water. Perfect health.',
        text: 'Animated counters introduce the purifier range, then product cards with starting prices and a clear enquire-or-buy button on a bold brand-blue band.',
        image: img('newmax-aqua', 's3'),
      },
      {
        label: 'The Future',
        title: 'Power your future with the sun.',
        text: 'Solar gets its own chapter, covering water heaters, power plants and savings on electricity bills, with EMI options called out for customers weighing the cost.',
        image: img('newmax-aqua', 's4'),
      },
    ],
    mobile: [img('newmax-aqua', 'm0'), img('newmax-aqua', 'm1'), img('newmax-aqua', 'm2')],
    mobileText: 'Both branch phone numbers and a WhatsApp button stay one tap away on mobile, because a leaking purifier is not something people fill in a form for.',
  },
  {
    id: 'vijayaa-alloy',
    title: 'Vijayaa Alloy',
    shortTitle: 'Vijayaa Alloy',
    link: '/projects/vijayaa-alloy',
    liveLink: 'https://www.vijayaalloy.com/',
    domain: 'vijayaalloy.com',
    img: img('vijayaa-alloy', 'cover'),
    date: '2026',
    company: 'Vijayaa Alloy Sdn. Bhd.',
    sector: 'Metal Recycling',
    location: 'Selangor, Malaysia',
    country: 'Malaysia',
    role: 'Design & Development',
    stack: ['Next.js', 'Swiper', 'English / Malay SEO', 'WhatsApp leads'],
    tagline: 'Turning scrap into value for factories across the Klang Valley.',
    featured: false,
    primary: '#243A5E',
    secondary: '#F4F5F7',
    accentColor: '#FFFFFF',
    fillColor: '#E1E8F0',
    menuColor: '#243A5E',
    menuFontColor: '#F4F5F7',
    fluidColor: '#3492DC',
    facts: [
      { value: '7', label: 'Recycling services' },
      { value: 'Free', label: 'RORO bin placement' },
      { value: 'Same day', label: 'Payment after weighing' },
    ],
    story: [
      {
        label: 'The Brief',
        title: 'Found by a factory manager, on a phone.',
        text: 'Vijayaa Alloy buys and recycles scrap metal across Selangor and the Klang Valley: aluminium, copper, steel, iron and whole factories being dismantled. Customers search in English and in Malay ("besi buruk"), often from a factory floor.',
        image: img('vijayaa-alloy', 's0'),
      },
      {
        label: 'The Services',
        title: 'Comprehensive scrap and recycling.',
        text: 'Seven services, including metal recycling, copper and aluminium, factory dismantling, free RORO bins, machinery removal and export logistics, sit in a swipeable row of photo cards.',
        image: img('vijayaa-alloy', 's1'),
      },
      {
        label: 'The Credibility',
        title: 'Featured in the news.',
        text: 'In a trade where trust decides who gets the load, a feature in The Star about recycling and waste separation gets its own section.',
        image: img('vijayaa-alloy', 's2'),
      },
      {
        label: 'The Materials',
        title: 'What we accept.',
        text: 'Every material category, from metal and cable to industrial, copper, stainless and aluminium scrap, is shown with a real photograph of the material, so sellers can match what is in their yard at a glance.',
        image: img('vijayaa-alloy', 's3'),
      },
      {
        label: 'The Close',
        title: 'Turn your scrap into value.',
        text: 'The page ends on one idea and three buttons: contact us, or WhatsApp either of two numbers. Search copy is written for "scrap metal buyer" and "pembeli besi buruk" alike.',
        image: img('vijayaa-alloy', 's4'),
      },
    ],
    mobile: [img('vijayaa-alloy', 'm0'), img('vijayaa-alloy', 'm1'), img('vijayaa-alloy', 'm2')],
    mobileText: 'The real signboard of the yard leads the mobile hero, so a first-time seller knows exactly where to drive, and WhatsApp is never more than a thumb away.',
  },
];

export const featuredProjects = projects.filter((project) => project.featured);

export default projects;
